[project]
name = "aevorex-backend"
version = "0.1.0"
description = "Aevorex Backend (FinanceHub + API)"
authors = [{name = "Csanád V.", email = "csanad@example.com"}]
requires-python = ">=3.10"
dependencies = []
